### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by amitdo** [hafontia/Ferdoka-One#1]
Hi Ben!

Is this Hebrew font considered ready to be used, or is it still in alpha/beta stage? I ask because I didn't find 'Fredoka-One' with Hebrew glyphs in other sites.

**Comment by hafontia-zz** [comment]
Hi Amit!

I wrote google to get an update on this issue, thanks!
The Hebrew is done and ready to use. I hope it will go online soon.

Cheers!

**Comment by amitdo** [comment]
Thank you.
